//
//  StyleKitName.swift
//  LedsControl
//
//  Created by Alessio Roberto on 23/02/2017.
//  Copyright (c) 2017 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

import UIKit

public class StyleKitName : NSObject {

    //// Cache

    private struct Cache {
        static let green: UIColor = UIColor(red: 0.045, green: 0.695, blue: 0.344, alpha: 1.000)
    }

    //// Colors

    public class var green: UIColor { return Cache.green }
}
